version: "3.7"
services:
  # dockerized database only for dev stage
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  kafka_akhq:
    build: ./kafka_akhq
    ports:
      - "8081:8080"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_akhq:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
    # NOPE command: sleep 10 && /opt/kafka/bin/kafka-topics.sh --create --bootstrap-server 0.0.0.0:9092 --replication-factor 1 --partitions 1 --topic topic1
    # connect from host to 127.0.0.1:8081 (akhq) and create the topic1 manually
  producers:
    build: ./producers
    depends_on:
      - "kafka_akhq"
    environment:
      KAFKA_IP: kafka_akhq
      KAFKA_PORT: 9092
  consumers:
    build: ./consumers
    environment:
      KAFKA_IP: kafka_akhq
      KAFKA_PORT: 9092
      KAFKA_GROUP: topic1-reader
    depends_on:
      - "kafka_akhq"
